/**
 * @fileOverview This file defines a Genkit flow that suggests improvements to a user-provided text prompt
 * to enhance image generation results.
 *
 * @fileOverview
 * - `suggestPromptImprovements`: Asynchronously suggests improvements to a given text prompt.
 * - `SuggestPromptImprovementsInput`: Interface defining the input for the prompt improvement suggestion.
 * - `SuggestPromptImprovementsOutput`: Interface defining the output containing the suggested improvements.
 */

'use server';

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestPromptImprovementsInputSchema = z.object({
  prompt: z.string().describe('The original text prompt provided by the user.'),
});

export type SuggestPromptImprovementsInput = z.infer<
  typeof SuggestPromptImprovementsInputSchema
>;

const SuggestPromptImprovementsOutputSchema = z.object({
  improvedPrompt: z
    .string()
    .describe(
      'The improved text prompt, incorporating suggestions for better image generation.'
    ),
  reasoning: z
    .string()
    .describe(
      'Explanation of why the prompt was modified and how the change improves image generation.'
    ),
});

export type SuggestPromptImprovementsOutput = z.infer<
  typeof SuggestPromptImprovementsOutputSchema
>;

export async function suggestPromptImprovements(
  input: SuggestPromptImprovementsInput
): Promise<SuggestPromptImprovementsOutput> {
  return suggestPromptImprovementsFlow(input);
}

const suggestPromptImprovementsPrompt = ai.definePrompt({
  name: 'suggestPromptImprovementsPrompt',
  input: {schema: SuggestPromptImprovementsInputSchema},
  output: {schema: SuggestPromptImprovementsOutputSchema},
  prompt: `You are an AI prompt engineer specializing in improving text prompts for image generation.

  Given the original prompt, provide an improved prompt that is more likely to produce a high-quality image.
  Explain your reasoning for the changes, focusing on how the changes will improve the image generation result.

  Original Prompt: {{{prompt}}}

  Improved Prompt:`, // Improved prompt will be generated by the model.
});

const suggestPromptImprovementsFlow = ai.defineFlow(
  {
    name: 'suggestPromptImprovementsFlow',
    inputSchema: SuggestPromptImprovementsInputSchema,
    outputSchema: SuggestPromptImprovementsOutputSchema,
  },
  async input => {
    const {output} = await suggestPromptImprovementsPrompt(input);
    return output!;
  }
);
